// js/data.js
const eventsData = [
  {
    id: "event1",
    title: "AI Healthcare Symposium",
    description:
      "A symposium on the latest advancements in AI applications in healthcare, featuring guest speakers from leading research institutions.",
    category: "academic",
    capacity: 150,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["AI", "Healthcare", "Symposium", "Research"],
    date: "2025-08-15",
    startTime: "09:00",
    endTime: "17:00",
    timezone: "UTC+05:30",
    eventType: "physical",
    location: "University Auditorium",
    organizerName: "Faculty of Medicine",
    organizerEmail: "med@example.com",
    requiresRegistration: true,
    requiresApproval: false,
    limitedCapacity: true,
    status: "approved",
    attendees: 120,
    isFeatured: true,
  },
  {
    id: "event2",
    title: "Machine Learning Workshop",
    description:
      "Hands-on workshop covering fundamental machine learning algorithms and practical implementation using Python.",
    category: "workshop",
    capacity: 50,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["ML", "Python", "Workshop", "Coding"],
    date: "2025-08-20",
    startTime: "10:00",
    endTime: "16:00",
    timezone: "UTC+05:30",
    eventType: "hybrid",
    location: "Computer Lab 3",
    virtualLink: "https://zoom.us/j/mlworkshop",
    organizerName: "Computer Science Department",
    organizerEmail: "cs@example.com",
    requiresRegistration: true,
    requiresApproval: false,
    limitedCapacity: true,
    status: "approved",
    attendees: 45,
    isFeatured: false,
  },
  {
    id: "event3",
    title: "Annual Sports Meet",
    description: "The biggest sports event of the year, featuring various athletic competitions and team sports.",
    category: "sports",
    capacity: 500,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["Sports", "Athletics", "Competition"],
    date: "2025-09-01",
    startTime: "08:00",
    endTime: "18:00",
    timezone: "UTC+05:30",
    eventType: "physical",
    location: "University Stadium",
    organizerName: "Sports Council",
    organizerEmail: "sports@example.com",
    requiresRegistration: false,
    requiresApproval: false,
    limitedCapacity: false,
    status: "approved",
    attendees: 300,
    isFeatured: true,
  },
  {
    id: "event4",
    title: "Career Fair 2025",
    description: "Connect with top companies and explore internship and job opportunities across various industries.",
    category: "career",
    capacity: 300,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["Career", "Jobs", "Internship", "Recruitment"],
    date: "2025-09-10",
    startTime: "09:30",
    endTime: "16:30",
    timezone: "UTC+05:30",
    eventType: "physical",
    location: "Main Exhibition Hall",
    organizerName: "Career Guidance Unit",
    organizerEmail: "career@example.com",
    requiresRegistration: true,
    requiresApproval: false,
    limitedCapacity: false,
    status: "pending", // Example pending event
    attendees: 0,
    isFeatured: false,
  },
  {
    id: "event5",
    title: "Cultural Night: A Celebration of Diversity",
    description: "An evening showcasing the rich cultural diversity of our university through music, dance, and drama.",
    category: "cultural",
    capacity: 400,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["Culture", "Arts", "Music", "Dance"],
    date: "2025-09-25",
    startTime: "18:00",
    endTime: "22:00",
    timezone: "UTC+05:30",
    eventType: "physical",
    location: "Open Air Theatre",
    organizerName: "Cultural Society",
    organizerEmail: "cultural@example.com",
    requiresRegistration: false,
    requiresApproval: false,
    limitedCapacity: false,
    status: "approved",
    attendees: 250,
    isFeatured: false,
  },
  {
    id: "event6",
    title: "Introduction to Web Development",
    description: "A beginner-friendly workshop on HTML, CSS, and JavaScript to kickstart your web development journey.",
    category: "workshop",
    capacity: 60,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["WebDev", "HTML", "CSS", "JavaScript"],
    date: "2025-08-22",
    startTime: "14:00",
    endTime: "17:00",
    timezone: "UTC+05:30",
    eventType: "virtual",
    virtualLink: "https://meet.google.com/webdev",
    organizerName: "Coding Club",
    organizerEmail: "codingclub@example.com",
    requiresRegistration: true,
    requiresApproval: false,
    limitedCapacity: true,
    status: "pending", // Another pending event
    attendees: 0,
    isFeatured: false,
  },
  {
    id: "event7",
    title: "Research Paper Writing Seminar",
    description: "Learn the best practices for writing and publishing high-quality research papers in your field.",
    category: "research",
    capacity: 80,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["Research", "Writing", "Academic"],
    date: "2025-08-28",
    startTime: "11:00",
    endTime: "13:00",
    timezone: "UTC+05:30",
    eventType: "hybrid",
    location: "Seminar Room 1",
    virtualLink: "https://zoom.us/j/researchseminar",
    organizerName: "Research Council",
    organizerEmail: "research@example.com",
    requiresRegistration: true,
    requiresApproval: true,
    limitedCapacity: false,
    status: "rejected", // Example rejected event
    reviewComments: "Description is too vague. Please provide more specific topics to be covered.",
    attendees: 0,
    isFeatured: false,
  },
  {
    id: "event8",
    title: "University Freshers' Welcome Party",
    description:
      "A social gathering to welcome new students to the university. Mingle, make new friends, and enjoy the music!",
    category: "social",
    capacity: 600,
    image: "/placeholder.svg?height=600&width=1200",
    tags: ["Social", "Freshers", "Party", "Welcome"],
    date: "2025-08-10",
    startTime: "19:00",
    endTime: "23:00",
    timezone: "UTC+05:30",
    eventType: "physical",
    location: "University Grounds",
    organizerName: "Student Affairs",
    organizerEmail: "studentaffairs@example.com",
    requiresRegistration: false,
    requiresApproval: false,
    limitedCapacity: false,
    status: "approved",
    attendees: 550,
    isFeatured: false,
  },
]

const notificationsData = [
  {
    id: "notif1",
    sender: "Admin",
    message: "Your AI Healthcare Symposium has been approved.",
    time: "2 minutes ago",
    profilePicture: "/placeholder.svg?height=40&width=40&text=Admin",
  },
  {
    id: "notif2",
    sender: "CS Dept",
    message: "Machine Learning Workshop registration is now open.",
    time: "1 hour ago",
    profilePicture: "/placeholder.svg?height=40&width=40&text=CS",
  },
  {
    id: "notif3",
    sender: "Sports Council",
    message: "Basketball tournament starts tomorrow.",
    time: "3 hours ago",
    profilePicture: "/placeholder.svg?height=40&width=40&text=SC",
  },
]

const trendingEventsData = [
  { id: "trending1", title: "Study Group: Calculus II", time: "Tomorrow 7PM", attendees: 23 },
  { id: "trending2", title: "Photography Club Meeting", time: "Friday 4PM", attendees: 45 },
  { id: "trending3", title: "Debate Society Practice", time: "Saturday 2PM", attendees: 18 },
]

const suggestedEventsData = [
  { id: "suggested1", title: "Data Science Workshop", reason: "Based on your Computer Science major" },
  { id: "suggested2", title: "Tech Startup Meetup", reason: "3 friends are interested" },
]
